# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Автоматически заполняемое поле для URL-ссылки.', verbose_name='Имя для URL-ссылки')),
                ('text', models.TextField()),
                ('date_published', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Посты пользователей',
                'verbose_name': 'Пост пользователя',
            },
        ),
        migrations.CreateModel(
            name='PersonalBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('feeds', models.ManyToManyField(blank=True, related_name='feeds', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, related_name='posts', to='main_site.BlogPost')),
            ],
            options={
                'verbose_name_plural': 'Блоги пользователей',
                'verbose_name': 'Блог пользователя',
            },
        ),
    ]
