# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0002_auto_20170514_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalblog',
            name='feeds',
            field=models.ManyToManyField(blank=True, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalblog',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalblog',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main_site.BlogPost'),
        ),
    ]
