# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20170514_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='already_sent',
            field=models.BooleanField(default=False),
        ),
    ]
