# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_blogpost_already_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='order_to_sent',
            field=models.BooleanField(default=False, verbose_name='Разослать уведомления?'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='already_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомления разосланы'),
        ),
    ]
