# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_auto_20170514_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(verbose_name='Имя для URL-ссылки'),
        ),
    ]
