# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_auto_20170514_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
