# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_blogpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
    ]
