# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('feeds', models.ManyToManyField(blank=True, related_name='feeds', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Блог пользователя',
                'verbose_name_plural': 'Блоги пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Пост пользователя', 'verbose_name_plural': 'Посты пользователей'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Автоматически заполняемое поле для URL-ссылки.', verbose_name='Имя для URL-ссылки'),
        ),
        migrations.AddField(
            model_name='personalblog',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main_site.BlogPost'),
        ),
    ]
